export default {
    LOAD_USER_BIKE_LIST: 'LOAD_USER_BIKE_LIST',
    LOAD_BIKE_BY_ID: 'LOAD_BIKE_BY_ID',
    LOAD_COMPO_BY_ID: 'LOAD_COMPO_BY_ID',
    LOGIN_USER_STRAVA: 'LOGIN_USER_STRAVA',
    CHECK_CORRECT_USER: 'CHECK_CORRECT_USER'
};
